<a href="https://colab.research.google.com/github/noctxrne/DSA-ICT/blob/main/NumPy_%26_Pandas_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy**

In [29]:
#1. Create a NumPy array with values from 10 to 49 (inclusive).
# ● Reshape it into a 4x10 matrix.
# ● Then extract the last column from the reshaped matrix

import numpy as np
a1=np.arange(10,50)
a2=np.reshape(a1,(4,10))
print(a2)
print(a2[:9,9])


[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[19 29 39 49]


In [34]:
# 2. Create two 3×3 matrices:
# One filled with all 5s , One with values from 1 to 9
# ● Add the two matrices
# ● Multiply them element-wise
# ● Then find the transpose of the result

A = np.full((3, 3), 5)
B = np.arange(1, 10).reshape(3, 3)
add=A+B
print("Sum:")
print(add)
multiply=A*B
print("Product:")
print(multiply)
transposes=np.transpose(multiply)
print("Transpose:")
print(transposes)

Sum:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
Product:
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
Transpose:
[[ 5 20 35]
 [10 25 40]
 [15 30 45]]


In [37]:
# 3. Create a NumPy array of 15 random integers between 10 and 100.
# ● Replace all values greater than 50 with -1
# ● Count how many values were replaced.

X=np.random.randint(10,101,size=15)
print(X)
replaced=np.where(X>50,-1,X)
print(replaced)
count= np.sum(replaced==-1)
print(count)


[100  23  67  56  68  79  18  29  26  36  71  73  11  58  71]
[-1 23 -1 -1 -1 -1 18 29 26 36 -1 -1 11 -1 -1]
9


In [44]:
# 4. Generate a 5×4 array with random values between 0 and 1 (float).
# ● Find the row with the maximum sum of values.
# ● Normalize each row using the formula

ax = np.random.rand(5, 4)
print(ax)
ax_new=ax.sum(axis=1)
print(ax_new)
max=np.max(ax_new)
print(max)

#Normalise
row_min = ax.min(axis=1).reshape(-1, 1)
row_max = ax.max(axis=1).reshape(-1, 1)
normalised=(ax-row_min)/(row_max-row_min)
print(normalised)

[[0.35193795 0.14106956 0.76561329 0.79348767]
 [0.10352351 0.48035933 0.89334002 0.96485845]
 [0.31108266 0.02577586 0.11599824 0.19180801]
 [0.95558698 0.86320028 0.41138357 0.13883569]
 [0.52441779 0.92118907 0.51160295 0.04619428]]
[2.05210847 2.44208132 0.64466476 2.36900652 2.00340408]
2.442081320991044
[[0.32321051 0.         0.95727528 1.        ]
 [0.         0.43750207 0.91696793 1.        ]
 [1.         0.         0.31622933 0.58194248]
 [1.         0.88688515 0.33369752 0.        ]
 [0.54654441 1.         0.53189879 0.        ]]


In [48]:
# 5. arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
# ● Find all unique elements
# ● Find the duplicates (elements that appear more than once)

arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
print("Unique:")
print(np.unique(arr))
elements,counts=np.unique(arr, return_counts=True)
duplicates = elements[counts > 1]
print("Duplicates:")
print(duplicates)

Unique:
[1 3 5 7 9]
Duplicates:
[1 3 5]


In [58]:
# 6. Create a 6×6 NumPy array with values from 1 to 36.
# ● Extract the middle 4×4 submatrix.
# ● Then extract all even numbers from this submatrix

arr1=np.arange(1,37).reshape(6,6)
print(arr1)
extracted=arr1[1:-1,1:-1]
print(extracted)
even=extracted[extracted%2==0]
print(even)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]
[ 8 10 14 16 20 22 26 28]


In [64]:
# 7. Generate an array of shape (3, 4) with values from 0 to 11.
# ● Reshape it to (2, 6)
# ● Then flatten it into a 1D array
# ● Convert the 1D array back to shape (4, 3)

array=np.arange(0,12).reshape(3,4)
print(array)
print("Reshape it to (2, 6) :")
print(array.reshape(2, 6))
print("Then flatten it into a 1D array :")
print(array.flatten())
print("Convert the 1D array back to shape (4, 3): ")
print(array.reshape(4, 3))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshape it to (2, 6) :
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Then flatten it into a 1D array :
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Convert the 1D array back to shape (4, 3): 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [70]:
# 8 . Create an array: a = np.array([[1, 2], [3, 4]])
# ● Append a new row [5, 6]
# ● Then append a new column [7, 8, 9]

a = np.array([[1,2],[3,4]])
print(a)
a=np.vstack([a,[5,6]])
print(a)
a=np.column_stack([a,[7, 8, 9]])
print(a)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]
 [5 6 9]]


In [73]:
# 9.
# a = np.array([1, 2, 3])
# b = np.array([4, 5, 6])
# c = np.array([7, 8, 9])
# ● Join them into a single array
# ● Reshape the result into a 3×3 matrix
# ● Extract the diagonal elements

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

arrconc= np.concatenate((a, b, c))
print(arrconc)
matrix=arrconc.reshape(3, 3)
print(matrix)
diag=np.diagonal(matrix)
print(diag)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


In [80]:
# 10. Create a NumPy array of integers from 1 to 20.
# ● Extract all values that are divisible by 3 or 5.
# ● Count how many such values exist.

array=np.arange(1,20)
print(array)
divisible=array[(array%3==0) | (array%5==0)]
print(divisible)
divisible.size

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 3  5  6  9 10 12 15 18]


8

# **Pandas**

In [124]:
import seaborn as sns
data=sns.load_dataset("titanic")
# print(data)

# 1. Load the Titanic dataset and display the first 10 rows.
print("\nLoad the Titanic dataset and display the first 10 rows.")
tenRows=data[:10]
print(tenRows)

#2. Find the number of missing values in each column.
print("\nFind the number of missing values in each column.")
data.isna().sum()

#3. Find the percentage of passengers who survived, grouped by gender.
print("\nFind the percentage of passengers who survived, grouped by gender.")

survived_male=(data["survived"]==1) & (data["sex"]=='male')
survived_female=(data["survived"]==1) & (data["sex"]=='female')
percentage_male=((survived_male.sum())/(data["sex"] == 'male').sum())*100
percentage_female=((survived_female.sum())/(data["sex"] == 'female').sum())*100
print(f"Survived Percentage of male is {percentage_male}")
print(f"Survived Percentage of female is {percentage_female}")

# 4. Find the average, median, and standard deviation of passenger ages
print("\nFind the average, median, and standard deviation of passenger ages.")

age=data["age"]
print(f"Mean: {np.mean(age)}")
print(f"Median: {np.median(age)}")
print(f"Standard Deviation: {np.std(age)}")

# 5. Count how many passengers were in each class (pclass)
print("\nCount how many passengers were in each class (pclass)")

firstCount=(data["class"]=='First').sum()
secondCount=(data["class"]=='Second').sum()
thirdCount=(data["class"]=='Third').sum()
print(f"First class had {firstCount}")
print(f"Second class had {secondCount}")
print(f"Third class had {thirdCount}")

# 6. Show all passengers who were female, under age 18, and survived.
print("\nShow all passengers who were female, under age 18, and survived.")

selected=data[(data["survived"]==1) & (data["sex"]=='female') &  (data["age"]<18)]
print(selected)

# 7. Replace missing age values with the median age.
# age = age.fillna(age.median())
print("\nReplace missing age values with the median age.")

age = np.where(age.isna(), age.median(), age)
print(age)

# 8. Create a column age_group with values:
# a. 'Child' for age < 18
# b. 'Adult' for age 18–60
# c. 'Senior' for age > 60

print("\nCreate a column age_group with values")

conditions = [data['age'] < 18, (data['age'] >= 18) & (data['age'] < 60), data['age']>60]
values = ['Child','Adult', 'Senior']
data['age_group'] = np.select(conditions, values, default='Unknown')
print(data)

# 9. Display the top 5 passengers who paid the highest fare
print("\nDisplay the top 5 passengers who paid the highest fare")

highest=data.sort_values("fare",ascending=False)
print(highest.head())

#10. Find the average fare paid, grouped by both pclass and sex.
print("\nFind the average fare paid, grouped by both pclass and sex.")
data.groupby(['pclass', 'sex'])['fare'].mean().round(2)

# 11. Rename the following columns:
# a. 'sex' → 'gender'
# b. 'fare' → 'ticket_fare'
print("\nRename the following columns")
data.rename(columns = {'sex': 'gender', 'fare':'ticket_fare'}, inplace=True)
data.head()

# 12. Count the number of passengers who survived and didn’t survive, grouped by class.
print("\nCount the number of passengers who survived and didn’t survive, grouped by class.")
print(data.groupby(['pclass', 'survived']).size())

# 13. Find the average age of passengers grouped by both class and gender.
print("\nFind the average age of passengers grouped by both class and gender.")
print(data.groupby(['pclass', 'gender'])['age'].mean().round(2))


Load the Titanic dataset and display the first 10 rows.
   survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton   